export const blogPosts = [
    {
        id: 1,
        title: "Introduction to JavaScript",
        content: "JavaScript is a versatile programming language...",
        author: "John Doe",
        date: "2023-01-01",
    },
    {
        id: 2,
        title: "CSS Styling Tips",
        content: "Learn how to create beautiful and responsive web designs with CSS...",
        author: "Jane Smith",
        date: "2023-01-05",
    },
    {
        id: 3,
        title: "Node.js and Express for Backend Development",
        content: "Explore the world of server-side JavaScript with Node.js and Express...",
        author: "Alex Johnson",
        date: "2023-01-10",
    },
    {
        id: 4,
        title: "React.js and Redux for Frontend Development",
        content: "Learn how to build dynamic and interactive web applications with React.js and Redux...",
        author: "Emily Davis",
        date: "2023-01-15",
    }, 
    {
        id: 5,
        title: "Angular.js and TypeScript for Frontend Development",
        content: "Explore the world of front-end web development with Angular.js and TypeScript...",
        author: "Michael Wilson",
        date: "2023-01-20",
    },
    {
        id: 6,
        title: "Vue.js and Composition API for Frontend Development",
        content: "Learn how to build modern and reactive web applications with Vue.js and Composition API...",
        author: "Olivia Taylor",
        date: "2023-01-25",
    },
    {
        id: 7,
        title: "Introduction to Git and GitHub",
        content: "Explore the world of version control with Git and GitHub...",
        author: "James Anderson",
        date: "2023-01-30",
    },
    {
        id: 8,
        title: "Introduction to GraphQL",
        content: "Explore the world of data querying with GraphQL...",
        author: "Sophia Jackson",
        date: "2023-02-05",
    },
    {  
        id: 9,
        title: "Introduction to GraphQL",
        content: "Explore the world of data querying with GraphQL...",
        author: "Sophia Jackson",
        date: "2023-02-05",
    },
    {
        id: 10,
        title: "Introduction to GraphQL",
        content: "Explore the world of data querying with GraphQL...",
        author: "Sophia Jackson",
        date: "2023-02-05",
    }
]